import { ROOM_TYPES } from './constants';
<<<<<<< HEAD
export const SEED_VERSION = 'capsu-v9';

export const initialRooms = [];

export const initialProfessors = [
  { id: 'P01', name: 'Aguilos, Ma. Relie', department: 'BSCS', specialization: ['GEM 101', 'GE 107'], maxUnits: 15 },
  { id: 'P02', name: 'Aller, Regine', department: 'BSOA', specialization: ['OAC 121', 'GEE 109'], maxUnits: 15 },
  { id: 'P03', name: 'Azarcon, Kimberly', department: 'BSCS', specialization: ['PE 110', 'GEE 103'], maxUnits: 17 },
  { id: 'P04', name: 'Ballera, Janice', department: 'BSCS', specialization: ['PE 112'], maxUnits: 16 },
  { id: 'P05', name: 'Baje, Sherra', department: 'BSCS', specialization: ['CS 108', 'CS 107'], maxUnits: 10 },
  { id: 'P06', name: 'Baranda, Herman', department: 'BSCS', specialization: ['NSTP 102'], maxUnits: 18 },
  { id: 'P07', name: 'Barrientos, Lenie', department: 'BSFT', specialization: ['FT 110', 'FT 107', 'FT 122'], maxUnits: 23 },
  { id: 'P08', name: 'Bernabe, Cynthren', department: 'BSOA', specialization: ['OAEL 113', 'OAC 123', 'GE 107'], maxUnits: 15 },
  { id: 'P09', name: 'Bobier, Lecel', department: 'BSFT', specialization: ['Physics 101', 'Chem 104', 'Thesis 101'], maxUnits: 13 },
  { id: 'P10', name: 'Braña, Nicolas IV', department: 'BSCS', specialization: ['CS 103', 'CS 107'], maxUnits: 30 },
  { id: 'P11', name: 'Bunda, Vincent', department: 'BSOA', specialization: ['GEE 102', 'GE 108', 'Res 101'], maxUnits: 12 },
  { id: 'P12', name: 'Corcino, Lida', department: 'BSCS', specialization: ['GE 106'], maxUnits: 12 },
  { id: 'P13', name: 'Dalida, Julie', department: 'BSCS', specialization: ['GE 108'], maxUnits: 12 },
  { id: 'P14', name: 'Dela Cena, Nino', department: 'BSCS', specialization: ['CS 110', 'CS 111'], maxUnits: 20 },
  { id: 'P15', name: 'Delgado, Freden', department: 'BAEL', specialization: ['OAC 117', 'ELS 101', 'ELS 199', 'Cognate 142', 'ELS 112'], maxUnits: 15 },
  { id: 'P16', name: 'Espartero, Michelle', department: 'BSOA', specialization: ['OAC 114', 'OAC 118', 'GEE 106', 'GE 107'], maxUnits: 15 },
  { id: 'P17', name: 'Filosofo, Merlyn', department: 'BSFT', specialization: ['Math 101'], maxUnits: 16 },
  { id: 'P18', name: 'Garbosa, June Rey', department: 'BAEL', specialization: ['GE 107', 'GE 109', 'NSTP 102'], maxUnits: 18 },
  { id: 'P19', name: 'Hilapad, Marife', department: 'BSFT', specialization: ['FT 114'], maxUnits: 6 },
  { id: 'P20', name: 'Iligan, Bethel Jane', department: 'BSFT', specialization: ['FT 113', 'FT 122'], maxUnits: 24 },
  { id: 'P21', name: 'Leccio, Clyde', department: 'BSFT', specialization: ['FT 107', 'FT 112'], maxUnits: 24 },
  { id: 'P22', name: 'Leonor, Lillibeth', department: 'BSFT', specialization: ['GEE 108'], maxUnits: 6 },
  { id: 'P23', name: 'Llanera, Olga', department: 'BSCS', specialization: ['CS 108', 'CS 118'], maxUnits: 24 },
  { id: 'P24', name: 'Llorito, Rica', department: 'BAEL', specialization: ['ELSM 122', 'ELSM 123', 'ELS 110', 'Cognate 134', 'Cognate 148', 'GE 106'], maxUnits: 18 },
  { id: 'P25', name: 'Luces, Rosemarie', department: 'BSOA', specialization: ['OAC 113', 'OAC 122', 'GEE 102'], maxUnits: 15 },
  { id: 'P26', name: 'Lotilla, Ramy Lloyd', department: 'BSOA', specialization: ['Res 101'], maxUnits: 3 },
  { id: 'P27', name: 'Lorenzo, Edzil', department: 'BSFT', specialization: ['FT 105', 'FT 115'], maxUnits: 10 },
  { id: 'P28', name: 'Magbanua, Virginia', department: 'BAEL', specialization: ['ELS 102', 'ELSM 124', 'ELSM 125', 'Cognate 139'], maxUnits: 12 },
  { id: 'P29', name: 'Marcos, Meschel', department: 'BSOA', specialization: ['OAEL 116', 'GE 109'], maxUnits: 9 },
  { id: 'P30', name: 'Martinez, Shiela', department: 'BSCS', specialization: ['GEM 101', 'GE 103', 'GEE 102'], maxUnits: 18 },
  { id: 'P31', name: 'Navarrosa, Frocy', department: 'BSCS', specialization: ['CS 109', 'GE 104'], maxUnits: 12 },
  { id: 'P32', name: 'Osuyos, Art Jayson', department: 'BSCS', specialization: ['OJT', 'Free Elective 102', 'Seminar 301', 'CS 109'], maxUnits: 24 },
  { id: 'P33', name: 'Palomar, Joy', department: 'BSCS', specialization: ['CS 120'], maxUnits: 6 },
  { id: 'P34', name: 'Paredes, Jelly', department: 'BSCS', specialization: ['CS 119', 'Seminar 301'], maxUnits: 12 },
  { id: 'P35', name: 'Pula, Leo', department: 'BSCS', specialization: ['CS 124', 'Free Elective 104'], maxUnits: 24 },
  { id: 'P36', name: 'Ricardo, Lalaine', department: 'BSCS', specialization: ['GE 109'], maxUnits: 12 },
  { id: 'P37', name: 'Suresca, Beljay', department: 'BSFT', specialization: ['Elective 2', 'FT 121', 'FT 115L'], maxUnits: 23 },
  { id: 'P38', name: 'Ticar, Rhodora', department: 'BSFT', specialization: ['Chem 102', 'GEE 103'], maxUnits: 11 },
  { id: 'P39', name: 'Victoriano, Maria Aurora', department: 'BAEL', specialization: ['ELS 103', 'FL 103', 'ELSM 128', 'FL 101'], maxUnits: 12 },
  { id: 'P40', name: 'Vista, Judith', department: 'BSCS', specialization: ['CS 116', 'CS 117'], maxUnits: 20 }
];

export const initialSubjects = [
  { id: 'S01', code: 'GEM 101', name: 'Life and Works of Rizal', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S02', code: 'GE 107', name: 'Ethics', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S03', code: 'OAC 121', name: 'Internet Research for Business', department: 'BSOA', credits: 3, requiredLab: true, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S04', code: 'GEE 109', name: 'Entrepreneurial Mind', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S05', code: 'PE 110', name: 'PATHFit 2', department: 'BSCS', credits: 2, requiredLab: false, hoursPerMeeting: 2, hoursPerWeek: 2 },
  { id: 'S06', code: 'GEE 103', name: 'Living in the IT Era', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S07', code: 'PE 112', name: 'PATHFit 4', department: 'BSCS', credits: 2, requiredLab: false, hoursPerMeeting: 2, hoursPerWeek: 2 },
  { id: 'S08', code: 'CS 108', name: 'Information Management', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S09', code: 'CS 107', name: 'Applications Development & Emerging Technolog', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S10', code: 'NSTP 102', name: 'ROTC/CWTS/LTS', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S11', code: 'FT 110', name: 'Food Processing II', department: 'BSFT', credits: 4.25, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S12', code: 'FT 107', name: 'Food Microbiology', department: 'BSFT', credits: 7.5, requiredLab: true, hoursPerMeeting: 3, hoursPerWeek: 9 },
  { id: 'S13', code: 'FT 122', name: 'Environmental Sustainability in the Food Industry', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S14', code: 'OAEL 113', name: 'Customer Analytics', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S15', code: 'OAC 123', name: 'Entrepreneurial Behavior and Competencies', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S16', code: 'Physics 101', name: 'Applied Physics', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S17', code: 'Chem 104', name: 'General Biochemistry', department: 'BSCS', credits: 4.25, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S18', code: 'Thesis 101', name: 'Thesis', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S19', code: 'CS 103', name: 'Computer Programming 1', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S20', code: 'GEE 102', name: 'Gender and Society', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S21', code: 'GE 108', name: 'Science Technology and Society', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S22', code: 'Res 101', name: 'Research Methods 1', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S23', code: 'GE 106', name: 'Purposive Communication', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S24', code: 'CS 110', name: 'Object Oriented Programming', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S25', code: 'CS 111', name: 'Software Engineering 2', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S26', code: 'OAC 117', name: 'Business Report Wwriting', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S27', code: 'ELS 101', name: 'Introduction to the English Language System', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S28', code: 'ELS 199', name: 'Language Research 1: Methodology', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S29', code: 'Cognate 142', name: 'Language and Journalism', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S30', code: 'ELS 112', name: 'Computer-mediated Communication', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S31', code: 'OAC 114', name: 'Advanced Shorthand', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S32', code: 'OAC 118', name: 'Office Administration Internship 300 hrs', department: 'BSOA', credits: 3, requiredLab: true, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S33', code: 'GEE 106', name: 'Philippine Popular Culture', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S34', code: 'Math 101', name: 'Calculus', department: 'BSFT', credits: 5, requiredLab: false, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S35', code: 'GE 109', name: 'Readings in Philippine History', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S36', code: 'FT 114', name: 'Food Safety', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S37', code: 'FT 113', name: 'Food Analysis', department: 'BSFT', credits: 7.5, requiredLab: true, hoursPerMeeting: 3, hoursPerWeek: 9 },
  { id: 'S38', code: 'FT 112', name: 'Food Engineering', department: 'BSFT', credits: 7.5, requiredLab: true, hoursPerMeeting: 3, hoursPerWeek: 9 },
  { id: 'S39', code: 'CS 118', name: 'Thesis 1', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S40', code: 'ELSM 122', name: 'Psychology of Language', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S41', code: 'ELSM 123', name: 'Multimodal Communication', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S42', code: 'ELS 110', name: 'Language of Literary Text', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S43', code: 'Cognate 134', name: 'Intructional Material Development and Evaluation', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S44', code: 'Cognate 148', name: 'Intercultural Communication', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S45', code: 'OAC 113', name: 'Administrative Office Procedures and Managemen', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S46', code: 'OAC 122', name: 'Events Management', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S47', code: 'FT 105', name: 'Business Management and Entrepreneurship', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S48', code: 'FT 115', name: 'Food Packaging and Labelling', department: 'BSFT', credits: 2, requiredLab: false, hoursPerMeeting: 2, hoursPerWeek: 2 },
  { id: 'S49', code: 'ELS 102', name: 'Theories of Language and Language Acquisition', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S50', code: 'ELSM 124', name: 'Language and Gender', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S51', code: 'ELSM 125', name: 'Language and Power', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S52', code: 'GEE 108', name: 'Environmental Science', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S53', code: 'Cognate 139', name: 'Business Communication', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S54', code: 'OAEL 116', name: 'Medical Office Internship 300 hrs or Legal Office Internship 300 hrs', department: 'BSOA', credits: 3, requiredLab: true, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S55', code: 'GE 103', name: 'Art Appreciation', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S56', code: 'CS 109', name: 'Discrete Structures 1', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S57', code: 'GE 104', name: 'Mathematics in the Modern World', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S58', code: 'OJT', name: 'On-The-Job Training (200hours)', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S59', code: 'Free Elective 102', name: 'Photo Editing and Video Editing', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S60', code: 'Seminar 301', name: 'Computer Seminar', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S61', code: 'CS 120', name: 'Business Analytics', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S62', code: 'CS 119', name: 'Information Assurance and Security', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S63', code: 'CS 124', name: 'Automata and Language Theory', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S64', code: 'Free Elective 104', name: 'Computer System Services', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S65', code: 'Elective 2', name: 'Meat Science and Technology', department: 'BSFT', credits: 4.25, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S66', code: 'FT 121', name: 'Undergraduate Seminar', department: 'BSFT', credits: 1, requiredLab: false, hoursPerMeeting: 1, hoursPerWeek: 1 },
  { id: 'S67', code: 'FT 115L', name: 'Food Packaging and Labelling (Lab)', department: 'BSFT', credits: 2.25, requiredLab: true, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S68', code: 'Chem 102', name: 'Qualitative Chemistry', department: 'BSFT', credits: 4.25, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S69', code: 'ELS 103', name: 'History of the English Language', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S70', code: 'FL 103', name: 'Foreign Language 3', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S71', code: 'ELSM 128', name: 'Philippine English', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S72', code: 'FL 101', name: 'Foreign Language 1', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S73', code: 'CS 116', name: 'Design and Implementation of Programming Langs', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S74', code: 'CS 117', name: 'Computer Architecture & Assembly Programming', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 }
];

export const initialSections = [
  { id: 'SEC01', name: 'BSCS 1A', program: 'BS Computer Science', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S19', 'S20', 'S23', 'S21', 'S02', 'S35'] },
  { id: 'SEC02', name: 'BSCS 1B', program: 'BS Computer Science', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S19', 'S23', 'S21', 'S02', 'S20', 'S35'] },
  { id: 'SEC03', name: 'BSCS 1C', program: 'BS Computer Science', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S02', 'S19', 'S23', 'S21', 'S20', 'S35'] },
  { id: 'SEC04', name: 'BSCS 1D', program: 'BS Computer Science', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S19', 'S23', 'S21', 'S02', 'S20', 'S35'] },
  { id: 'SEC05', name: 'BSCS 2A', program: 'BS Computer Science', yearLevel: 2, studentCount: 40, subjects: ['S01', 'S07', 'S24', 'S25', 'S08', 'S56'] },
  { id: 'SEC06', name: 'BSCS 2B', program: 'BS Computer Science', yearLevel: 2, studentCount: 40, subjects: ['S01', 'S07', 'S09', 'S24', 'S25', 'S08', 'S56'] },
  { id: 'SEC07', name: 'BSCS 2C', program: 'BS Computer Science', yearLevel: 2, studentCount: 40, subjects: ['S01', 'S07', 'S09', 'S24', 'S25', 'S08', 'S56'] },
  { id: 'SEC08', name: 'BSCS 2D', program: 'BS Computer Science', yearLevel: 2, studentCount: 40, subjects: ['S07', 'S08', 'S09', 'S24', 'S25', 'S01', 'S56'] },
  { id: 'SEC09', name: 'BAEL 1', program: 'BA English Language', yearLevel: 1, studentCount: 40, subjects: ['S02', 'S05', 'S27', 'S35', 'S10', 'S49', 'S69'] },
  { id: 'SEC10', name: 'BAEL 2', program: 'BA English Language', yearLevel: 2, studentCount: 40, subjects: ['S06', 'S07', 'S40', 'S41', 'S50', 'S72'] },
  { id: 'SEC11', name: 'BSFT 1A', program: 'BS Food Technology', yearLevel: 1, studentCount: 40, subjects: ['S02', 'S34'] },
  { id: 'SEC12', name: 'BSFT 1', program: 'BS Food Technology', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S16', 'S23', 'S68'] },
  { id: 'SEC13', name: 'BSFT 2A', program: 'BS Food Technology', yearLevel: 2, studentCount: 40, subjects: ['S07', 'S12', 'S17', 'S35', 'S47', 'S06'] },
  { id: 'SEC14', name: 'BSFT 2B', program: 'BS Food Technology', yearLevel: 2, studentCount: 40, subjects: ['S07', 'S12', 'S17', 'S35', 'S47', 'S06'] },
  { id: 'SEC15', name: 'BSFT 3A', program: 'BS Food Technology', yearLevel: 3, studentCount: 40, subjects: ['S11', 'S36', 'S37', 'S38', 'S52', 'S48', 'S67'] },
  { id: 'SEC16', name: 'BSFT 3B', program: 'BS Food Technology', yearLevel: 3, studentCount: 40, subjects: ['S11', 'S36', 'S37', 'S38', 'S52', 'S48', 'S67'] },
  { id: 'SEC17', name: 'BSFT 4A', program: 'BS Food Technology', yearLevel: 4, studentCount: 40, subjects: ['S04', 'S18', 'S13', 'S01', 'S65', 'S66'] },
  { id: 'SEC18', name: 'BSFT 4B', program: 'BS Food Technology', yearLevel: 4, studentCount: 40, subjects: ['S04', 'S18', 'S13', 'S01', 'S65', 'S66'] },
  { id: 'SEC19', name: 'BSFT 4C', program: 'BS Food Technology', yearLevel: 4, studentCount: 40, subjects: ['S04', 'S13', 'S18', 'S01', 'S65'] },
  { id: 'SEC20', name: 'BSOA 1', program: 'BS Office Administration', yearLevel: 1, studentCount: 40, subjects: ['S10', 'S20', 'S31', 'S45', 'S55', 'S57'] },
  { id: 'SEC21', name: 'BSOA 2', program: 'BS Office Administration', yearLevel: 2, studentCount: 40, subjects: ['S07', 'S21', 'S26', 'S32', 'S35'] },
  { id: 'SEC22', name: 'BSOA 3A', program: 'BS Office Administration', yearLevel: 3, studentCount: 40, subjects: ['S03', 'S14', 'S15', 'S33', 'S46', 'S22'] },
  { id: 'SEC23', name: 'BSOA 3B', program: 'BS Office Administration', yearLevel: 3, studentCount: 40, subjects: ['S03', 'S14', 'S15', 'S22', 'S33', 'S46'] },
  { id: 'SEC24', name: 'BSOA', program: 'BS Office Administration', yearLevel: 1, studentCount: 40, subjects: ['S05'] },
  { id: 'SEC25', name: 'BAEL 3', program: 'BA English Language', yearLevel: 3, studentCount: 40, subjects: ['S28', 'S42', 'S43', 'S51', 'S70'] },
  { id: 'SEC26', name: 'BAEL 4', program: 'BA English Language', yearLevel: 4, studentCount: 40, subjects: ['S29', 'S30', 'S44', 'S53', 'S71'] },
  { id: 'SEC27', name: 'BSCS 3A', program: 'BS Computer Science', yearLevel: 3, studentCount: 40, subjects: ['S39', 'S59', 'S60', 'S61', 'S62', 'S73', 'S74'] },
  { id: 'SEC28', name: 'BSCS 3B', program: 'BS Computer Science', yearLevel: 3, studentCount: 40, subjects: ['S39', 'S59', 'S60', 'S61', 'S62', 'S73', 'S74'] },
  { id: 'SEC29', name: 'BSCS 3C', program: 'BS Computer Science', yearLevel: 3, studentCount: 40, subjects: ['S39', 'S59', 'S60', 'S62', 'S73'] },
  { id: 'SEC30', name: 'BSOA 4A', program: 'BS Office Administration', yearLevel: 4, studentCount: 40, subjects: ['S54'] },
  { id: 'SEC31', name: 'BSOA 4B', program: 'BS Office Administration', yearLevel: 4, studentCount: 40, subjects: ['S54'] },
  { id: 'SEC32', name: 'BSCS 4A', program: 'BS Computer Science', yearLevel: 4, studentCount: 40, subjects: ['S58', 'S63', 'S64'] },
  { id: 'SEC33', name: 'BSCS 4B', program: 'BS Computer Science', yearLevel: 4, studentCount: 40, subjects: ['S58', 'S63', 'S64'] },
  { id: 'SEC34', name: 'BSCS 4C', program: 'BS Computer Science', yearLevel: 4, studentCount: 40, subjects: ['S58', 'S63', 'S64'] }
];
=======
export const SEED_VERSION = 'capsu-v3';

export const initialSemesters = [
  { id: 'sem_1', name: '1st Semester 2026-2027', isActive: true },
  { id: 'sem_2', name: '2nd Semester 2026-2027', isActive: false },
  { id: 'summer_1', name: 'Summer 2026', isActive: false }
];

// src/initial.js
// CAPSU Mambusao Official Data (Loading_2nd-2025-2026 superfinal) - CLEANED

export const initialRooms = [
  { id: "R_ScienceLab", name: "Science Lab", type: "Laboratory", hasComputers: true, hasProjector: true },
  { id: "R_GymFTE", name: "Gym FTE", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_FoodPro", name: "Food Pro", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_PhysicoChem", name: "Physico Chem", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_FTELectRoom", name: "FTE Lect Room", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Flavier", name: "Flavier", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Gym4", name: "Gym 4", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Gym3", name: "Gym 3", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Gym2", name: "Gym 2", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Gym", name: "Gym", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Stage", name: "Stage", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_MULTIMEDIAROOM", name: "MULTIMEDIA ROOM", type: "Laboratory", hasComputers: true, hasProjector: true },
  { id: "R_GS7", name: "GS 7", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS6", name: "GS 6", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS5", name: "GS 5", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS4", name: "GS 4", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS3", name: "GS 3", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS2", name: "GS 2", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS1", name: "GS 1", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_SpeechLab", name: "Speech Lab", type: "Laboratory", hasComputers: true, hasProjector: true },
  { id: "R_Room204", name: "Room 204", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Room203", name: "Room 203", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Room102", name: "Room 102", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Room101", name: "Room 101", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB6", name: "NB 6", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB5", name: "NB 5", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB4", name: "NB 4", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB3", name: "NB 3", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB2", name: "NB 2", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB1", name: "NB 1", type: "Lecture", hasComputers: false, hasProjector: true }
];

export const initialProfessors = [
  { id: "P_0", name: "Ma. Relie Aguilos", department: "General Education", maxUnits: 24, specialization: ["S_GEM101", "S_GE107"], preferredRooms: [] },
  { id: "P_1", name: "Regine Aller", department: "General Education", maxUnits: 24, specialization: ["S_OAC121", "S_GEE109"], preferredRooms: [] },
  { id: "P_2", name: "Kimberly Azarcon", department: "General Education", maxUnits: 24, specialization: ["S_PE110", "S_GEE103"], preferredRooms: [] },
  { id: "P_3", name: "Janice Ballera", department: "General Education", maxUnits: 24, specialization: ["S_PE112"], preferredRooms: [] },
  { id: "P_4", name: "Sherra Baje", department: "Computer Science", maxUnits: 24, specialization: ["S_CS107", "S_CS108"], preferredRooms: [] },
  { id: "P_5", name: "Herman Baranda", department: "General Education", maxUnits: 24, specialization: ["S_NSTP102"], preferredRooms: [] },
  { id: "P_6", name: "Cynthren Bernabe", department: "General Education", maxUnits: 24, specialization: ["S_GE107"], preferredRooms: [] },
  { id: "P_7", name: "Lecel Bobier", department: "General Education", maxUnits: 24, specialization: ["S_OAC114"], preferredRooms: [] },
  { id: "P_8", name: "Nicolas Bra├▒a", department: "Computer Science", maxUnits: 24, specialization: ["S_CS107lec", "S_CS103"], preferredRooms: [] },
  { id: "P_9", name: "Vincent Bunda", department: "General Education", maxUnits: 24, specialization: ["S_GEE102"], preferredRooms: [] },
  { id: "P_10", name: "Lida Corcino", department: "General Education", maxUnits: 24, specialization: ["S_GE106"], preferredRooms: [] },
  { id: "P_11", name: "Julie Dalida", department: "General Education", maxUnits: 24, specialization: ["S_GE108"], preferredRooms: [] },
  { id: "P_12", name: "Nino Dela Cena", department: "Computer Science", maxUnits: 24, specialization: ["S_CS111"], preferredRooms: [] },
  { id: "P_13", name: "Freden Delgado", department: "General Education", maxUnits: 24, specialization: ["S_ELSM119", "S_ELSC111", "S_OAC117"], preferredRooms: [] },
  { id: "P_14", name: "Mischelle Espartero", department: "General Education", maxUnits: 24, specialization: ["S_GE107"], preferredRooms: [] },
  { id: "P_15", name: "Merlyn Filosofo", department: "General Education", maxUnits: 24, specialization: ["S_FL103", "S_CBM102", "S_ELSM119", "S_ELSM115"], preferredRooms: [] },
  { id: "P_16", name: "Bethel Jane Iligan", department: "General Education", maxUnits: 24, specialization: ["S_OAC111", "S_CBM102"], preferredRooms: [] },
  { id: "P_17", name: "June Rey Garbosa", department: "General Education", maxUnits: 24, specialization: ["S_GE109"], preferredRooms: [] },
  { id: "P_18", name: "Marife Hilapad", department: "General Education", maxUnits: 24, specialization: ["S_FTC107", "S_FTC111"], preferredRooms: [] },
  { id: "P_19", name: "Lillibeth Leonor", department: "General Education", maxUnits: 24, specialization: ["S_GE108", "S_FTC105"], preferredRooms: [] },
  { id: "P_20", name: "Olga Llanera", department: "Computer Science", maxUnits: 24, specialization: ["S_CS108", "S_CS118"], preferredRooms: [] },
  { id: "P_21", name: "Ricah Llorito", department: "General Education", maxUnits: 24, specialization: ["S_GE106"], preferredRooms: [] },
  { id: "P_22", name: "Rosemarie Luces", department: "General Education", maxUnits: 24, specialization: ["S_GEE102"], preferredRooms: [] },
  { id: "P_23", name: "Virginia Magbanua", department: "General Education", maxUnits: 24, specialization: ["S_OAC114"], preferredRooms: [] },
  { id: "P_24", name: "Meschel Marcos", department: "General Education", maxUnits: 24, specialization: ["S_CBM102", "S_ELSM115", "S_ELSM121"], preferredRooms: [] },
  { id: "P_25", name: "Lizel Marquez", department: "General Education", maxUnits: 24, specialization: ["S_FTM102", "S_FTE103", "S_FTM106"], preferredRooms: [] },
  { id: "P_26", name: "Shiela Martinez", department: "General Education", maxUnits: 24, specialization: ["S_GEM101", "S_GE103"], preferredRooms: [] },
  { id: "P_27", name: "Frocy Navarrosa", department: "Computer Science", maxUnits: 24, specialization: ["S_CS109"], preferredRooms: [] },
  { id: "P_28", name: "Art Jayson Osuyos", department: "Computer Science", maxUnits: 24, specialization: ["S_FreeElective102lec", "S_CS110", "S_FreeElective102", "S_CS109"], preferredRooms: [] },
  { id: "P_29", name: "Cherry Joy Palomar", department: "Computer Science", maxUnits: 24, specialization: ["S_CS120", "S_CSElective102"], preferredRooms: [] },
  { id: "P_30", name: "Jelly Paredes", department: "Computer Science", maxUnits: 24, specialization: ["S_CS119", "S_Seminar301"], preferredRooms: [] },
  { id: "P_31", name: "Leo Pula", department: "General Education", maxUnits: 24, specialization: ["S_FreeElective104", "S_ELS110"], preferredRooms: [] },
  { id: "P_32", name: "Lalaine Ricardo", department: "General Education", maxUnits: 24, specialization: ["S_GE109"], preferredRooms: [] },
  { id: "P_33", name: "Rhodora Ticar", department: "General Education", maxUnits: 24, specialization: ["S_GEE103", "S_Chem102"], preferredRooms: [] },
  { id: "P_34", name: "Maria Aurora Victoriano", department: "General Education", maxUnits: 24, specialization: ["S_FL103", "S_FL101", "S_ELSM128", "S_ELS103"], preferredRooms: [] },
  { id: "P_35", name: "Judith Vista", department: "Computer Science", maxUnits: 24, specialization: ["S_CS117", "S_CS116"], preferredRooms: [] },

];

export const initialSubjects = [
  { id: "S_GEM101", code: "GEM 101", name: "Life and Works of Rizal", credits: 3.0, requiredLab: false },
  { id: "S_GE107", code: "GE 107", name: "Ethics", credits: 3.0, requiredLab: false },
  { id: "S_OAC121", code: "OAC 121", name: "Internet Research for Business", credits: 3.0, requiredLab: true },
  { id: "S_GEE109", code: "GEE 109", name: "Entrepreneurial Mind", credits: 3.0, requiredLab: false },
  { id: "S_PE110", code: "PE 110", name: "PATHFit 2", credits: 2.0, requiredLab: false },
  { id: "S_GEE103", code: "GEE 103", name: "Living in the IT Era", credits: 3.0, requiredLab: false },
  { id: "S_PE112", code: "PE 112", name: "PATHFit 4", credits: 2.0, requiredLab: false },
  { id: "S_CS107", code: "CS 107", name: "Intro. to Human-Computer Interaction", credits: 3.0, requiredLab: true },
  { id: "S_CS108", code: "CS 108", name: "Programming 2", credits: 3.0, requiredLab: true },
  { id: "S_NSTP102", code: "NSTP 102", name: "CWTS 2", credits: 3.0, requiredLab: false },
  { id: "S_OAC114", code: "OAC 114", name: "Administrative Office Procedures", credits: 3.0, requiredLab: false },
  { id: "S_CS107lec", code: "CS 107 (lec)", name: "Intro. to Human-Computer Interaction", credits: 3.0, requiredLab: false },
  { id: "S_CS103", code: "CS 103", name: "Intro to Computing", credits: 3.0, requiredLab: true },
  { id: "S_GEE102", code: "GEE 102", name: "The Contemporary World", credits: 3.0, requiredLab: false },
  { id: "S_GE106", code: "GE 106", name: "Purposive Communication", credits: 3.0, requiredLab: false },
  { id: "S_GE108", code: "GE 108", name: "Science, Technology, and Society", credits: 3.0, requiredLab: false },
  { id: "S_CS111", code: "CS 111", name: "IT Elective 1", credits: 3.0, requiredLab: true },
  { id: "S_OAC117", code: "OAC 117", name: "Business Report Writing", credits: 3.0, requiredLab: false },
  { id: "S_ELSM119", code: "ELSM 119", name: "Language Programs and Policies in Multilingual Societies", credits: 3.0, requiredLab: false },
  { id: "S_ELSC111", code: "ELSC 111", name: "Sanaysay at Talumpati", credits: 3.0, requiredLab: false },
  { id: "S_CBM102", code: "CBM 102", name: "Human Resource Management", credits: 3.0, requiredLab: false },
  { id: "S_ELSM115", code: "ELSM 115", name: "Literary Criticism", credits: 3.0, requiredLab: false },
  { id: "S_FL103", code: "FL 103", name: "Foreign Language 3", credits: 3.0, requiredLab: false },
  { id: "S_OAC111", code: "OAC 111", name: "Business Communication", credits: 3.0, requiredLab: false },
  { id: "S_GE109", code: "GE 109", name: "Readings in Philippine History", credits: 3.0, requiredLab: false },
  { id: "S_FTC107", code: "FTC 107", name: "Chemistry for Food Science", credits: 5.0, requiredLab: true },
  { id: "S_FTC111", code: "FTC 111", name: "Physical Chemistry", credits: 5.0, requiredLab: true },
  { id: "S_FTC105", code: "FTC 105", name: "Food Microbiology", credits: 5.0, requiredLab: true },
  { id: "S_CS118", code: "CS 118", name: "Software Engineering II", credits: 3.0, requiredLab: true },
  { id: "S_ELSM121", code: "ELSM 121", name: "Stylistics and Discourse Analysis", credits: 3.0, requiredLab: false },
  { id: "S_FTE103", code: "FTE 103", name: "Unit Operations in Food Processing I", credits: 3.0, requiredLab: false },
  { id: "S_FTM102", code: "FTM 102", name: "Post-Harvest Handling & Tech.", credits: 3.0, requiredLab: true },
  { id: "S_FTM106", code: "FTM 106", name: "Food Safety", credits: 3.0, requiredLab: true },
  { id: "S_GE103", code: "GE 103", name: "Mathematics in the Modern World", credits: 3.0, requiredLab: false },
  { id: "S_CS109", code: "CS 109", name: "Discrete Mathematics", credits: 3.0, requiredLab: false },
  { id: "S_FreeElective102", code: "Free Elective 102", name: "Free Elective 2", credits: 3.0, requiredLab: true },
  { id: "S_CS110", code: "CS 110", name: "Intro to Data Science", credits: 3.0, requiredLab: true },
  { id: "S_FreeElective102lec", code: "Free Elective 102 (lec)", name: "Free Elective 2", credits: 3.0, requiredLab: false },
  { id: "S_CSElective102", code: "CS Elective 102", name: "CS Elective 2", credits: 3.0, requiredLab: true },
  { id: "S_CS120", code: "CS 120", name: "Networks & Communications", credits: 3.0, requiredLab: true },
  { id: "S_CS119", code: "CS 119", name: "Information Assurance & Security", credits: 3.0, requiredLab: true },
  { id: "S_Seminar301", code: "Seminar 301", name: "Seminar and Field Trip", credits: 3.0, requiredLab: false },
  { id: "S_FreeElective104", code: "Free Elective 104", name: "Free Elective 4", credits: 3.0, requiredLab: true },
  { id: "S_ELS110", code: "ELS 110", name: "Survey of English and American Literature", credits: 3.0, requiredLab: false },
  { id: "S_Chem102", code: "Chem 102", name: "Qualitative Chemistry", credits: 5.0, requiredLab: true },
  { id: "S_FL101", code: "FL 101", name: "Foreign Language 1", credits: 3.0, requiredLab: false },
  { id: "S_ELS103", code: "ELS 103", name: "History of the English Language", credits: 3.0, requiredLab: false },
  { id: "S_ELSM128", code: "ELSM 128", name: "Philippine English", credits: 3.0, requiredLab: false },
  { id: "S_CS116", code: "CS 116", name: "Design and Implementation of Programming Language", credits: 5.0, requiredLab: true },
  { id: "S_CS117", code: "CS 117", name: "Computer Architecture & Assembly Programming", credits: 5.0, requiredLab: true },
  { id: "S_OAC123", code: "OAC 123", name: "Customer Relations", credits: 3.0, requiredLab: false },
  { id: "S_OAC119", code: "OAC 119", name: "Machine Shorthand", credits: 3.0, requiredLab: true },
  { id: "S_CS124", code: "CS 124", name: "Thesis Writing II", credits: 3.0, requiredLab: true },
  { id: "S_OJT", code: "OJT", name: "Practicum (162 hrs.)", credits: 3.0, requiredLab: false },
  { id: "S_FTC103", code: "FTC 103", name: "Food Processing", credits: 5.0, requiredLab: true },
  { id: "S_FTE107", code: "FTE 107", name: "Meat Processing", credits: 3.0, requiredLab: true },
  { id: "S_FTE106", code: "FTE 106", name: "Food Packaging and Labeling", credits: 3.0, requiredLab: true },
  { id: "S_ELSM117", code: "ELSM 117", name: "Afro-Asian Literature", credits: 3.0, requiredLab: false },
  { id: "S_OAEL116", code: "OAEL 116", name: "Events Management", credits: 3.0, requiredLab: false },
  { id: "S_FTE105", code: "FTE 105", name: "Product Development and Innovation", credits: 3.0, requiredLab: true }
];

export const initialSections = [
  { id: "SEC_BSCS2A", name: "BSCS 2A", subjects: ["S_CS107lec", "S_GEM101", "S_CS109", "S_CS111", "S_CS108", "S_PE112"] },
  { id: "SEC_BSCS2B", name: "BSCS 2B", subjects: ["S_CS107", "S_GEM101", "S_CS109", "S_CS111", "S_CS108", "S_CS110", "S_PE112"] },
  { id: "SEC_BSCS2C", name: "BSCS 2C", subjects: ["S_CS107lec", "S_GEM101", "S_CS109", "S_CS111", "S_CS108", "S_PE112"] },
  { id: "SEC_BAEL1", name: "BAEL 1", subjects: ["S_GE109", "S_GE107", "S_NSTP102", "S_ELS103", "S_PE110"] },
  { id: "SEC_BSFT1A", name: "BSFT 1A", subjects: ["S_GE109", "S_GE107", "S_NSTP102", "S_GE106", "S_PE110"] },
  { id: "SEC_BSOA3A", name: "BSOA 3A", subjects: ["S_OAC121"] },
  { id: "SEC_BSOA3B", name: "BSOA 3B", subjects: ["S_OAC121"] },
  { id: "SEC_BSFT4A", name: "BSFT 4A", subjects: ["S_GEM101", "S_GEE109"] },
  { id: "SEC_BSFT4B", name: "BSFT 4B", subjects: ["S_GEM101", "S_GEE109"] },
  { id: "SEC_BSFT4C", name: "BSFT 4C", subjects: ["S_GEM101", "S_GEE109"] },
  { id: "SEC_BSCS1A", name: "BSCS 1A", subjects: ["S_GE108", "S_CS103", "S_GE106", "S_PE110"] },
  { id: "SEC_BSCS1C", name: "BSCS 1C", subjects: ["S_GE109", "S_GE108", "S_GE106", "S_PE110"] },
  { id: "SEC_BSCS1B", name: "BSCS 1B", subjects: ["S_GE108", "S_CS103", "S_GE106", "S_PE110"] },
  { id: "SEC_BSFT2A", name: "BSFT 2A", subjects: ["S_GEE103", "S_FTC103", "S_FTM102", "S_FTE103", "S_PE112"] },
  { id: "SEC_BSFT2B", name: "BSFT 2B", subjects: ["S_GEE103", "S_FTC103", "S_FTM102", "S_FTE103", "S_PE112"] },
  { id: "SEC_BSCS2D", name: "BSCS 2D", subjects: ["S_CS107lec", "S_GEM101", "S_CS109", "S_CS111", "S_CS108", "S_PE112"] },
  { id: "SEC_BSFT1", name: "BSFT 1", subjects: ["S_GE108", "S_GE106", "S_Chem102"] },
  { id: "SEC_BSOA1", name: "BSOA 1", subjects: ["S_OAC114", "S_GE104", "S_NSTP102", "S_OAC111", "S_PE110"] },
  { id: "SEC_BAEL4", name: "BAEL 4", subjects: ["S_ELSM119", "S_ELSM128", "S_ELSM121"] },
  { id: "SEC_BAEL3", name: "BAEL 3", subjects: ["S_FL103", "S_ELSM115", "S_ELSM117"] },
  { id: "SEC_BSOA2", name: "BSOA 2", subjects: ["S_CBM102", "S_OAC117", "S_OAC119", "S_PE112"] },
  { id: "SEC_BSFT3A", name: "BSFT 3A", subjects: ["S_FTC105", "S_FTM106", "S_FTC107", "S_FTC111", "S_FTE105"] },
  { id: "SEC_BSFT3B", name: "BSFT 3B", subjects: ["S_FTC105", "S_FTC107", "S_FTE107", "S_FTE106"] },
  { id: "SEC_BSFT3C", name: "BSFT 3C", subjects: ["S_FTC105", "S_FTC107", "S_FTM106", "S_FTE107", "S_FTE106"] },
  { id: "SEC_BAEL2", name: "BAEL 2", subjects: ["S_ELSC111", "S_FL101", "S_ELS110", "S_PE112"] },
  { id: "SEC_BSCS1D", name: "BSCS 1D", subjects: ["S_GE109", "S_GE107", "S_NSTP102", "S_GE106"] },
  { id: "SEC_BSCS3A", name: "BSCS 3A", subjects: ["S_CS117", "S_CS116", "S_Seminar301", "S_FreeElective102lec", "S_CS120", "S_CS119", "S_CSElective102"] },
  { id: "SEC_BSCS3B", name: "BSCS 3B", subjects: ["S_CS117", "S_CS116", "S_Seminar301", "S_FreeElective102", "S_CS120", "S_CS119", "S_CSElective102"] },
  { id: "SEC_BSCS3C", name: "BSCS 3C", subjects: ["S_CS117", "S_CS118", "S_CS116", "S_Seminar301", "S_FreeElective102", "S_CS120", "S_CS119", "S_CSElective102"] },
  { id: "SEC_BSOA4A", name: "BSOA 4A", subjects: ["S_OAEL116"] },
  { id: "SEC_BSOA4B", name: "BSOA 4B", subjects: ["S_OAEL116"] },
  { id: "SEC_BSCS4A", name: "BSCS 4A", subjects: ["S_OJT", "S_CS124", "S_FreeElective104"] },
  { id: "SEC_BSCS4B", name: "BSCS 4B", subjects: ["S_OJT", "S_CS124", "S_FreeElective104"] },
  { id: "SEC_BSCS4C", name: "BSCS 4C", subjects: ["S_OJT", "S_CS124", "S_FreeElective104"] }
];
>>>>>>> ad90e23247e230ae52ea3aac88719739a45154e0
