import { ROOM_TYPES } from './constants';
export const SEED_VERSION = 'capsu-v11';

export const initialRooms = [];

export const initialProfessors = [
  { id: 'P01', name: 'Aguilos, Ma. Relie', department: 'BSCS', specialization: ['GEM 101', 'GE 107'], maxUnits: 15 },
  { id: 'P02', name: 'Aller, Regine', department: 'BSOA', specialization: ['OAC 121', 'GEE 109'], maxUnits: 15 },
  { id: 'P03', name: 'Azarcon, Kimberly', department: 'BSCS', specialization: ['PE 110', 'GEE 103'], maxUnits: 17 },
  { id: 'P04', name: 'Ballera, Janice', department: 'BSCS', specialization: ['PE 112'], maxUnits: 16 },
  { id: 'P05', name: 'Baje, Sherra', department: 'BSCS', specialization: ['CS 108', 'CS 107'], maxUnits: 10 },
  { id: 'P06', name: 'Baranda, Herman', department: 'BSCS', specialization: ['NSTP 102'], maxUnits: 18 },
  { id: 'P07', name: 'Barrientos, Lenie', department: 'BSFT', specialization: ['FT 110', 'FT 107', 'FT 122'], maxUnits: 23 },
  { id: 'P08', name: 'Bernabe, Cynthren', department: 'BSOA', specialization: ['OAEL 113', 'OAC 123', 'GE 107'], maxUnits: 15 },
  { id: 'P09', name: 'Bobier, Lecel', department: 'BSFT', specialization: ['Physics 101', 'Chem 104', 'Thesis 101'], maxUnits: 13 },
  { id: 'P10', name: 'Braña, Nicolas IV', department: 'BSCS', specialization: ['CS 103', 'CS 107'], maxUnits: 30 },
  { id: 'P11', name: 'Bunda, Vincent', department: 'BSOA', specialization: ['GEE 102', 'GE 108', 'Res 101'], maxUnits: 12 },
  { id: 'P12', name: 'Corcino, Lida', department: 'BSCS', specialization: ['GE 106'], maxUnits: 12 },
  { id: 'P13', name: 'Dalida, Julie', department: 'BSCS', specialization: ['GE 108'], maxUnits: 12 },
  { id: 'P14', name: 'Dela Cena, Nino', department: 'BSCS', specialization: ['CS 110', 'CS 111'], maxUnits: 20 },
  { id: 'P15', name: 'Delgado, Freden', department: 'BAEL', specialization: ['OAC 117', 'ELS 101', 'ELS 199', 'Cognate 142', 'ELS 112'], maxUnits: 15 },
  { id: 'P16', name: 'Espartero, Michelle', department: 'BSOA', specialization: ['OAC 114', 'OAC 118', 'GEE 106', 'GE 107'], maxUnits: 15 },
  { id: 'P17', name: 'Filosofo, Merlyn', department: 'BSFT', specialization: ['Math 101'], maxUnits: 16 },
  { id: 'P18', name: 'Garbosa, June Rey', department: 'BAEL', specialization: ['GE 107', 'GE 109', 'NSTP 102'], maxUnits: 18 },
  { id: 'P19', name: 'Hilapad, Marife', department: 'BSFT', specialization: ['FT 114'], maxUnits: 6 },
  { id: 'P20', name: 'Iligan, Bethel Jane', department: 'BSFT', specialization: ['FT 113', 'FT 122'], maxUnits: 24 },
  { id: 'P21', name: 'Leccio, Clyde', department: 'BSFT', specialization: ['FT 107', 'FT 112'], maxUnits: 24 },
  { id: 'P22', name: 'Leonor, Lillibeth', department: 'BSFT', specialization: ['GEE 108'], maxUnits: 6 },
  { id: 'P23', name: 'Llanera, Olga', department: 'BSCS', specialization: ['CS 108', 'CS 118'], maxUnits: 24 },
  { id: 'P24', name: 'Llorito, Rica', department: 'BAEL', specialization: ['ELSM 122', 'ELSM 123', 'ELS 110', 'Cognate 134', 'Cognate 148', 'GE 106'], maxUnits: 18 },
  { id: 'P25', name: 'Luces, Rosemarie', department: 'BSOA', specialization: ['OAC 113', 'OAC 122', 'GEE 102'], maxUnits: 15 },
  { id: 'P26', name: 'Lotilla, Ramy Lloyd', department: 'BSOA', specialization: ['Res 101'], maxUnits: 3 },
  { id: 'P27', name: 'Lorenzo, Edzil', department: 'BSFT', specialization: ['FT 105', 'FT 115'], maxUnits: 10 },
  { id: 'P28', name: 'Magbanua, Virginia', department: 'BAEL', specialization: ['ELS 102', 'ELSM 124', 'ELSM 125', 'Cognate 139'], maxUnits: 12 },
  { id: 'P29', name: 'Marcos, Meschel', department: 'BSOA', specialization: ['OAEL 116', 'GE 109'], maxUnits: 9 },
  { id: 'P30', name: 'Martinez, Shiela', department: 'BSCS', specialization: ['GEM 101', 'GE 103', 'GEE 102'], maxUnits: 18 },
  { id: 'P31', name: 'Navarrosa, Frocy', department: 'BSCS', specialization: ['CS 109', 'GE 104'], maxUnits: 12 },
  { id: 'P32', name: 'Osuyos, Art Jayson', department: 'BSCS', specialization: ['OJT', 'Free Elective 102', 'Seminar 301', 'CS 109'], maxUnits: 24 },
  { id: 'P33', name: 'Palomar, Joy', department: 'BSCS', specialization: ['CS 120'], maxUnits: 6 },
  { id: 'P34', name: 'Paredes, Jelly', department: 'BSCS', specialization: ['CS 119', 'Seminar 301'], maxUnits: 12 },
  { id: 'P35', name: 'Pula, Leo', department: 'BSCS', specialization: ['CS 124', 'Free Elective 104'], maxUnits: 24 },
  { id: 'P36', name: 'Ricardo, Lalaine', department: 'BSCS', specialization: ['GE 109'], maxUnits: 12 },
  { id: 'P37', name: 'Suresca, Beljay', department: 'BSFT', specialization: ['Elective 2', 'FT 121', 'FT 115L'], maxUnits: 23 },
  { id: 'P38', name: 'Ticar, Rhodora', department: 'BSFT', specialization: ['Chem 102', 'GEE 103'], maxUnits: 11 },
  { id: 'P39', name: 'Victoriano, Maria Aurora', department: 'BAEL', specialization: ['ELS 103', 'FL 103', 'ELSM 128', 'FL 101'], maxUnits: 12 },
  { id: 'P40', name: 'Vista, Judith', department: 'BSCS', specialization: ['CS 116', 'CS 117'], maxUnits: 20 }
];

export const initialSubjects = [
  { id: 'S01', code: 'GEM 101', name: 'Life and Works of Rizal', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S02', code: 'GE 107', name: 'Ethics', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S03', code: 'OAC 121', name: 'Internet Research for Business', department: 'BSOA', credits: 3, requiredLab: true, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S04', code: 'GEE 109', name: 'Entrepreneurial Mind', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S05', code: 'PE 110', name: 'PATHFit 2', department: 'BSCS', credits: 2, requiredLab: false, hoursPerMeeting: 2, hoursPerWeek: 2 },
  { id: 'S06', code: 'GEE 103', name: 'Living in the IT Era', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S07', code: 'PE 112', name: 'PATHFit 4', department: 'BSCS', credits: 2, requiredLab: false, hoursPerMeeting: 2, hoursPerWeek: 2 },
  { id: 'S08', code: 'CS 108', name: 'Information Management', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S09', code: 'CS 107', name: 'Applications Development & Emerging Technolog', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S10', code: 'NSTP 102', name: 'ROTC/CWTS/LTS', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S11', code: 'FT 110', name: 'Food Processing II', department: 'BSFT', credits: 4.25, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S12', code: 'FT 107', name: 'Food Microbiology', department: 'BSFT', credits: 7.5, requiredLab: true, hoursPerMeeting: 3, hoursPerWeek: 9 },
  { id: 'S13', code: 'FT 122', name: 'Environmental Sustainability in the Food Industry', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S14', code: 'OAEL 113', name: 'Customer Analytics', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S15', code: 'OAC 123', name: 'Entrepreneurial Behavior and Competencies', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S16', code: 'Physics 101', name: 'Applied Physics', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S17', code: 'Chem 104', name: 'General Biochemistry', department: 'BSCS', credits: 4.25, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S18', code: 'Thesis 101', name: 'Thesis', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S19', code: 'CS 103', name: 'Computer Programming 1', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S20', code: 'GEE 102', name: 'Gender and Society', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S21', code: 'GE 108', name: 'Science Technology and Society', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S22', code: 'Res 101', name: 'Research Methods 1', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S23', code: 'GE 106', name: 'Purposive Communication', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S24', code: 'CS 110', name: 'Object Oriented Programming', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S25', code: 'CS 111', name: 'Software Engineering 2', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S26', code: 'OAC 117', name: 'Business Report Wwriting', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S27', code: 'ELS 101', name: 'Introduction to the English Language System', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S28', code: 'ELS 199', name: 'Language Research 1: Methodology', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S29', code: 'Cognate 142', name: 'Language and Journalism', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S30', code: 'ELS 112', name: 'Computer-mediated Communication', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S31', code: 'OAC 114', name: 'Advanced Shorthand', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S32', code: 'OAC 118', name: 'Office Administration Internship 300 hrs', department: 'BSOA', credits: 3, requiredLab: true, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S33', code: 'GEE 106', name: 'Philippine Popular Culture', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S34', code: 'Math 101', name: 'Calculus', department: 'BSFT', credits: 5, requiredLab: false, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S35', code: 'GE 109', name: 'Readings in Philippine History', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S36', code: 'FT 114', name: 'Food Safety', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S37', code: 'FT 113', name: 'Food Analysis', department: 'BSFT', credits: 7.5, requiredLab: true, hoursPerMeeting: 3, hoursPerWeek: 9 },
  { id: 'S38', code: 'FT 112', name: 'Food Engineering', department: 'BSFT', credits: 7.5, requiredLab: true, hoursPerMeeting: 3, hoursPerWeek: 9 },
  { id: 'S39', code: 'CS 118', name: 'Thesis 1', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S40', code: 'ELSM 122', name: 'Psychology of Language', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S41', code: 'ELSM 123', name: 'Multimodal Communication', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S42', code: 'ELS 110', name: 'Language of Literary Text', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S43', code: 'Cognate 134', name: 'Intructional Material Development and Evaluation', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S44', code: 'Cognate 148', name: 'Intercultural Communication', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S45', code: 'OAC 113', name: 'Administrative Office Procedures and Managemen', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S46', code: 'OAC 122', name: 'Events Management', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S47', code: 'FT 105', name: 'Business Management and Entrepreneurship', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S48', code: 'FT 115', name: 'Food Packaging and Labelling', department: 'BSFT', credits: 2, requiredLab: false, hoursPerMeeting: 2, hoursPerWeek: 2 },
  { id: 'S49', code: 'ELS 102', name: 'Theories of Language and Language Acquisition', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S50', code: 'ELSM 124', name: 'Language and Gender', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S51', code: 'ELSM 125', name: 'Language and Power', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S52', code: 'GEE 108', name: 'Environmental Science', department: 'BSFT', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S53', code: 'Cognate 139', name: 'Business Communication', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S54', code: 'OAEL 116', name: 'Medical Office Internship 300 hrs or Legal Office Internship 300 hrs', department: 'BSOA', credits: 3, requiredLab: true, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S55', code: 'GE 103', name: 'Art Appreciation', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S56', code: 'CS 109', name: 'Discrete Structures 1', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S57', code: 'GE 104', name: 'Mathematics in the Modern World', department: 'BSOA', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S58', code: 'OJT', name: 'On-The-Job Training (200hours)', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S59', code: 'Free Elective 102', name: 'Photo Editing and Video Editing', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S60', code: 'Seminar 301', name: 'Computer Seminar', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S61', code: 'CS 120', name: 'Business Analytics', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S62', code: 'CS 119', name: 'Information Assurance and Security', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S63', code: 'CS 124', name: 'Automata and Language Theory', department: 'BSCS', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S64', code: 'Free Elective 104', name: 'Computer System Services', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S65', code: 'Elective 2', name: 'Meat Science and Technology', department: 'BSFT', credits: 4.25, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S66', code: 'FT 121', name: 'Undergraduate Seminar', department: 'BSFT', credits: 1, requiredLab: false, hoursPerMeeting: 1, hoursPerWeek: 1 },
  { id: 'S67', code: 'FT 115L', name: 'Food Packaging and Labelling (Lab)', department: 'BSFT', credits: 2.25, requiredLab: true, hoursPerMeeting: 3, hoursPerWeek: 3 },
  { id: 'S68', code: 'Chem 102', name: 'Qualitative Chemistry', department: 'BSFT', credits: 4.25, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S69', code: 'ELS 103', name: 'History of the English Language', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S70', code: 'FL 103', name: 'Foreign Language 3', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S71', code: 'ELSM 128', name: 'Philippine English', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S72', code: 'FL 101', name: 'Foreign Language 1', department: 'BAEL', credits: 3, requiredLab: false, hoursPerMeeting: 1.5, hoursPerWeek: 3 },
  { id: 'S73', code: 'CS 116', name: 'Design and Implementation of Programming Langs', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 },
  { id: 'S74', code: 'CS 117', name: 'Computer Architecture & Assembly Programming', department: 'BSCS', credits: 3, requiredLab: true, hoursPerMeeting: 2.5, hoursPerWeek: 5 }
];

export const initialSections = [
  { id: 'SEC01', name: 'BSCS 1A', program: 'BS Computer Science', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S19', 'S20', 'S23', 'S21', 'S02', 'S35'] },
  { id: 'SEC02', name: 'BSCS 1B', program: 'BS Computer Science', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S19', 'S23', 'S21', 'S02', 'S20', 'S35'] },
  { id: 'SEC03', name: 'BSCS 1C', program: 'BS Computer Science', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S02', 'S19', 'S23', 'S21', 'S20', 'S35'] },
  { id: 'SEC04', name: 'BSCS 1D', program: 'BS Computer Science', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S19', 'S23', 'S21', 'S02', 'S20', 'S35'] },
  { id: 'SEC05', name: 'BSCS 2A', program: 'BS Computer Science', yearLevel: 2, studentCount: 40, subjects: ['S01', 'S07', 'S24', 'S25', 'S08', 'S56'] },
  { id: 'SEC06', name: 'BSCS 2B', program: 'BS Computer Science', yearLevel: 2, studentCount: 40, subjects: ['S01', 'S07', 'S09', 'S24', 'S25', 'S08', 'S56'] },
  { id: 'SEC07', name: 'BSCS 2C', program: 'BS Computer Science', yearLevel: 2, studentCount: 40, subjects: ['S01', 'S07', 'S09', 'S24', 'S25', 'S08', 'S56'] },
  { id: 'SEC08', name: 'BSCS 2D', program: 'BS Computer Science', yearLevel: 2, studentCount: 40, subjects: ['S07', 'S08', 'S09', 'S24', 'S25', 'S01', 'S56'] },
  { id: 'SEC09', name: 'BAEL 1', program: 'BA English Language', yearLevel: 1, studentCount: 40, subjects: ['S02', 'S05', 'S27', 'S35', 'S10', 'S49', 'S69'] },
  { id: 'SEC10', name: 'BAEL 2', program: 'BA English Language', yearLevel: 2, studentCount: 40, subjects: ['S06', 'S07', 'S40', 'S41', 'S50', 'S72'] },
  { id: 'SEC11', name: 'BSFT 1A', program: 'BS Food Technology', yearLevel: 1, studentCount: 40, subjects: ['S02', 'S34'] },
  { id: 'SEC12', name: 'BSFT 1', program: 'BS Food Technology', yearLevel: 1, studentCount: 40, subjects: ['S05', 'S10', 'S16', 'S23', 'S68'] },
  { id: 'SEC13', name: 'BSFT 2A', program: 'BS Food Technology', yearLevel: 2, studentCount: 40, subjects: ['S07', 'S12', 'S17', 'S35', 'S47', 'S06'] },
  { id: 'SEC14', name: 'BSFT 2B', program: 'BS Food Technology', yearLevel: 2, studentCount: 40, subjects: ['S07', 'S12', 'S17', 'S35', 'S47', 'S06'] },
  { id: 'SEC15', name: 'BSFT 3A', program: 'BS Food Technology', yearLevel: 3, studentCount: 40, subjects: ['S11', 'S36', 'S37', 'S38', 'S52', 'S48', 'S67'] },
  { id: 'SEC16', name: 'BSFT 3B', program: 'BS Food Technology', yearLevel: 3, studentCount: 40, subjects: ['S11', 'S36', 'S37', 'S38', 'S52', 'S48', 'S67'] },
  { id: 'SEC17', name: 'BSFT 4A', program: 'BS Food Technology', yearLevel: 4, studentCount: 40, subjects: ['S04', 'S18', 'S13', 'S01', 'S65', 'S66'] },
  { id: 'SEC18', name: 'BSFT 4B', program: 'BS Food Technology', yearLevel: 4, studentCount: 40, subjects: ['S04', 'S18', 'S13', 'S01', 'S65', 'S66'] },
  { id: 'SEC19', name: 'BSFT 4C', program: 'BS Food Technology', yearLevel: 4, studentCount: 40, subjects: ['S04', 'S13', 'S18', 'S01', 'S65'] },
  { id: 'SEC20', name: 'BSOA 1', program: 'BS Office Administration', yearLevel: 1, studentCount: 40, subjects: ['S10', 'S20', 'S31', 'S45', 'S55', 'S57'] },
  { id: 'SEC21', name: 'BSOA 2', program: 'BS Office Administration', yearLevel: 2, studentCount: 40, subjects: ['S07', 'S21', 'S26', 'S32', 'S35'] },
  { id: 'SEC22', name: 'BSOA 3A', program: 'BS Office Administration', yearLevel: 3, studentCount: 40, subjects: ['S03', 'S14', 'S15', 'S33', 'S46', 'S22'] },
  { id: 'SEC23', name: 'BSOA 3B', program: 'BS Office Administration', yearLevel: 3, studentCount: 40, subjects: ['S03', 'S14', 'S15', 'S22', 'S33', 'S46'] },
  { id: 'SEC24', name: 'BSOA', program: 'BS Office Administration', yearLevel: 1, studentCount: 40, subjects: ['S05'] },
  { id: 'SEC25', name: 'BAEL 3', program: 'BA English Language', yearLevel: 3, studentCount: 40, subjects: ['S28', 'S42', 'S43', 'S51', 'S70'] },
  { id: 'SEC26', name: 'BAEL 4', program: 'BA English Language', yearLevel: 4, studentCount: 40, subjects: ['S29', 'S30', 'S44', 'S53', 'S71'] },
  { id: 'SEC27', name: 'BSCS 3A', program: 'BS Computer Science', yearLevel: 3, studentCount: 40, subjects: ['S39', 'S59', 'S60', 'S61', 'S62', 'S73', 'S74'] },
  { id: 'SEC28', name: 'BSCS 3B', program: 'BS Computer Science', yearLevel: 3, studentCount: 40, subjects: ['S39', 'S59', 'S60', 'S61', 'S62', 'S73', 'S74'] },
  { id: 'SEC29', name: 'BSCS 3C', program: 'BS Computer Science', yearLevel: 3, studentCount: 40, subjects: ['S39', 'S59', 'S60', 'S62', 'S73'] },
  { id: 'SEC30', name: 'BSOA 4A', program: 'BS Office Administration', yearLevel: 4, studentCount: 40, subjects: ['S54'] },
  { id: 'SEC31', name: 'BSOA 4B', program: 'BS Office Administration', yearLevel: 4, studentCount: 40, subjects: ['S54'] },
  { id: 'SEC32', name: 'BSCS 4A', program: 'BS Computer Science', yearLevel: 4, studentCount: 40, subjects: ['S58', 'S63', 'S64'] },
  { id: 'SEC33', name: 'BSCS 4B', program: 'BS Computer Science', yearLevel: 4, studentCount: 40, subjects: ['S58', 'S63', 'S64'] },
];

export const initialDepartments = [
  { id: 'BSCS', name: 'BSCS', color: '#109EEF' },
  { id: 'BAEL', name: 'BAEL', color: '#EAB308' },
  { id: 'BSOA', name: 'BSOA', color: '#8B5CF6' },
  { id: 'BSFT', name: 'BSFT', color: '#16A34A' }
];

export const initialCourses = [
  { id: 'C01', code: 'BSCS', title: 'Bachelor of Science in Computer Science', departmentId: 'BSCS' },
  { id: 'C02', code: 'BSFT', title: 'Bachelor of Science in Food Technology', departmentId: 'BSFT' },
  { id: 'C03', code: 'BSOA', title: 'Bachelor of Science in Office Administration', departmentId: 'BSOA' },
  { id: 'C04', code: 'BAEL', title: 'Bachelor of Arts in English Language', departmentId: 'BAEL' },
  { id: 'C05', code: 'BSIT', title: 'Bachelor of Science in Information Technology', departmentId: 'BSCS' }
];
