// src/initial.js
// Capiz State University - Mambusao Satellite College Manual Schedule Data

export const initialRooms = [
  { "id": "R_ScienceLab", "name": "Science Lab", "type": "Laboratory", "hasComputers": true, "hasProjector": true },
  { "id": "R_GymFTE", "name": "Gym FTE", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_FoodPro", "name": "Food Pro", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_PhysicoChem", "name": "Physico Chem", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_FTELectRoom", "name": "FTE Lect Room", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_Flavier", "name": "Flavier", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_Gym4", "name": "Gym 4", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_Gym3", "name": "Gym 3", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_Gym2", "name": "Gym 2", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_Gym", "name": "Gym", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_Stage", "name": "Stage", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_MULTIMEDIAROOM", "name": "MULTIMEDIA ROOM", "type": "Laboratory", "hasComputers": true, "hasProjector": true },
  { "id": "R_GS7", "name": "GS 7", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_GS6", "name": "GS 6", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_GS5", "name": "GS 5", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_GS4", "name": "GS 4", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_GS3", "name": "GS 3", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_GS2", "name": "GS 2", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_GS1", "name": "GS 1", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_SpeechLab", "name": "Speech Lab", "type": "Laboratory", "hasComputers": true, "hasProjector": true },
  { "id": "R_Room204", "name": "Room 204", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_Room203", "name": "Room 203", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_Room102", "name": "Room 102", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_Room101", "name": "Room 101", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_NB6", "name": "NB 6", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_NB5", "name": "NB 5", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_NB4", "name": "NB 4", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_NB3", "name": "NB 3", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_NB2", "name": "NB 2", "type": "Lecture", "hasComputers": false, "hasProjector": true },
  { "id": "R_NB1", "name": "NB 1", "type": "Lecture", "hasComputers": false, "hasProjector": true },
];

export const initialProfessors = [
  { "id": "P_0", "name": "Escleto, Marianne A.", "department": "General Education", "maxUnits": 24, "specialization": ["S_Math4"], "preferredRooms": [] },
  { "id": "P_1", "name": "Navarrosa, Frocy M.", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_Math11a", "S_Math21", "S_CP24", "S_CMSC51"], "preferredRooms": [] },
  { "id": "P_2", "name": "Concepcion, Magdalena B.", "department": "General Education", "maxUnits": 24, "specialization": ["S_Fil21", "S_Lit21", "S_Lit31"], "preferredRooms": [] },
  { "id": "P_3", "name": "Dionio, Rosel L.", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_CMSC131", "S_CMSC132", "S_CMSC141", "S_CP22"], "preferredRooms": [] },
  { "id": "P_4", "name": "Luces, Joein", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_CMSCElective", "S_FreeElective", "S_CMSC2", "S_CP12"], "preferredRooms": [] },
  { "id": "P_5", "name": "Lastimoso, Domingo Jr. L.", "department": "General Education", "maxUnits": 24, "specialization": ["S_English11", "S_English21", "S_English31", "S_English41"], "preferredRooms": [] },
  { "id": "P_6", "name": "Dalida, Julie V.", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_CMSC11", "S_CMSC12", "S_FreeElective"], "preferredRooms": [] },
  { "id": "P_7", "name": "Paredes, Jeffrey L.", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_CP24", "S_CMSC22", "S_CP14", "S_CP22"], "preferredRooms": [] },
  { "id": "P_8", "name": "Lamayo, Teresita J. V.", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_CP22", "S_CMSC21", "S_CP12", "S_CMSC12"], "preferredRooms": [] },
  { "id": "P_9", "name": "Llanera, Olga L.", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_CMSC142", "S_CMSC143", "S_CMSC133", "S_CMSC134"], "preferredRooms": [] },
  { "id": "P_10", "name": "Lozada, Jose A.", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_CP24", "S_CMSC51", "S_CMSC22"], "preferredRooms": [] },
  { "id": "P_11", "name": "Kapunan, Cornelio A.", "department": "General Education", "maxUnits": 24, "specialization": ["S_Philo21"], "preferredRooms": [] },
  { "id": "P_12", "name": "Bunda, Visitacion", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_CMSCElective", "S_CP24", "S_CMSC143", "S_CMSC142"], "preferredRooms": [] },
  { "id": "P_13", "name": "Atienza, Gilda L.", "department": "General Education", "maxUnits": 24, "specialization": ["S_English31", "S_Major11", "S_Major12", "S_Hum11"], "preferredRooms": [] },
  { "id": "P_14", "name": "Martinez, Sheila", "department": "General Education", "maxUnits": 24, "specialization": ["S_Spanish21", "S_NatSci21", "S_Physics21", "S_Biol22"], "preferredRooms": [] },
  { "id": "P_15", "name": "Garcia, Cesar", "department": "General Education", "maxUnits": 24, "specialization": ["S_Rizal21"], "preferredRooms": [] },
  { "id": "P_16", "name": "Bernabe, Cecilio", "department": "General Education", "maxUnits": 24, "specialization": ["S_Fil31"], "preferredRooms": [] },
  { "id": "P_17", "name": "Leonor, Lilibeth G.", "department": "General Education", "maxUnits": 24, "specialization": ["S_FTE05", "S_FTE07", "S_FTE16", "S_FTE20", "S_FTE21", "S_FTE22"], "preferredRooms": [] },
  { "id": "P_18", "name": "Valzado, Nelson L.", "department": "General Education", "maxUnits": 24, "specialization": ["S_FTE08", "S_FTE09", "S_FTE11", "S_FTE22"], "preferredRooms": [] },
  { "id": "P_19", "name": "Rosinas, Marlyn M.", "department": "General Education", "maxUnits": 24, "specialization": ["S_Major08", "S_Major10", "S_Major13", "S_FTE17", "S_FTE18", "S_FTE19"], "preferredRooms": [] },
  { "id": "P_20", "name": "Tiongson, Celsa", "department": "General Education", "maxUnits": 24, "specialization": ["S_Agri21"], "preferredRooms": [] },
  { "id": "P_21", "name": "Villasoto, Jodelyn L.", "department": "General Education", "maxUnits": 24, "specialization": ["S_Major11", "S_Major12", "S_Major14", "S_Major09"], "preferredRooms": [] },
  { "id": "P_22", "name": "Berondo, Nelson L.", "department": "Computer Science", "maxUnits": 24, "specialization": ["S_Typing2", "S_Steno2"], "preferredRooms": [] },
  { "id": "P_23", "name": "Mr. Y", "department": "General Education", "maxUnits": 24, "specialization": ["S_AppliedResearch2", "S_Speech11"], "preferredRooms": [] },
  { "id": "P_24", "name": "Llorito, Ricah", "department": "General Education", "maxUnits": 24, "specialization": ["S_Math11a", "S_Math21"], "preferredRooms": [] },
  { "id": "P_25", "name": "Espartero, M.", "department": "General Education", "maxUnits": 24, "specialization": ["S_CWTS", "S_ROTC"], "preferredRooms": [] },
  { "id": "P_26", "name": "Mr. X", "department": "General Education", "maxUnits": 24, "specialization": ["S_Hum11", "S_SocSci21"], "preferredRooms": [] },
  { "id": "P_27", "name": "Delgado, Freden S.", "department": "General Education", "maxUnits": 24, "specialization": ["S_English4", "S_English", "S_English21", "S_English41", "S_Major02"], "preferredRooms": [] },
  { "id": "P_28", "name": "Ticar, Erna", "department": "General Education", "maxUnits": 24, "specialization": ["S_SocSci21", "S_Socio41", "S_Elective01"], "preferredRooms": [] },
  { "id": "P_29", "name": "Pula, Leo T.", "department": "General Education", "maxUnits": 24, "specialization": ["S_English11", "S_Major0508", "S_Major0609"], "preferredRooms": [] },
];

export const initialSubjects = [
  { "id": "S_Math4", "code": "Math 4", "name": "Math 4", "credits": 5, "requiredLab": false },
  { "id": "S_Math11a", "code": "Math 11a", "name": "Math 11a", "credits": 3, "requiredLab": false },
  { "id": "S_Math21", "code": "Math 21", "name": "Math 21", "credits": 3, "requiredLab": false },
  { "id": "S_CP24", "code": "CP 24", "name": "CP 24", "credits": 3, "requiredLab": false },
  { "id": "S_CMSC51", "code": "CMSC 51", "name": "CMSC 51", "credits": 3, "requiredLab": true },
  { "id": "S_Fil21", "code": "Fil 21", "name": "Fil 21", "credits": 3, "requiredLab": false },
  { "id": "S_Lit21", "code": "Lit 21", "name": "Lit 21", "credits": 3, "requiredLab": false },
  { "id": "S_Lit31", "code": "Lit 31", "name": "Lit 31", "credits": 3, "requiredLab": false },
  { "id": "S_CMSC131", "code": "CMSC 131", "name": "CMSC 131", "credits": 8, "requiredLab": true },
  { "id": "S_CMSC132", "code": "CMSC 132", "name": "CMSC 132", "credits": 5, "requiredLab": true },
  { "id": "S_CMSC141", "code": "CMSC 141", "name": "CMSC 141", "credits": 3, "requiredLab": true },
  { "id": "S_CP22", "code": "CP 22", "name": "CP 22", "credits": 3, "requiredLab": false },
  { "id": "S_CMSCElective", "code": "CMSC Elective", "name": "CMSC Elective", "credits": 8, "requiredLab": true },
  { "id": "S_FreeElective", "code": "Free Elective", "name": "Free Elective", "credits": 8, "requiredLab": false },
  { "id": "S_CMSC2", "code": "CMSC 2", "name": "CMSC 2", "credits": 3, "requiredLab": true },
  { "id": "S_CP12", "code": "CP 12", "name": "CP 12", "credits": 3, "requiredLab": false },
  { "id": "S_English11", "code": "English 11", "name": "English 11", "credits": 3, "requiredLab": false },
  { "id": "S_English21", "code": "English 21", "name": "English 21", "credits": 3, "requiredLab": false },
  { "id": "S_English31", "code": "English 31", "name": "English 31", "credits": 3, "requiredLab": false },
  { "id": "S_English41", "code": "English 41", "name": "English 41", "credits": 3, "requiredLab": false },
  { "id": "S_CMSC11", "code": "CMSC 11", "name": "CMSC 11", "credits": 3, "requiredLab": true },
  { "id": "S_CMSC12", "code": "CMSC 12", "name": "CMSC 12", "credits": 3, "requiredLab": true },
  { "id": "S_CMSC22", "code": "CMSC 22", "name": "CMSC 22", "credits": 3, "requiredLab": true },
  { "id": "S_CP14", "code": "CP 14", "name": "CP 14", "credits": 3, "requiredLab": false },
  { "id": "S_CMSC21", "code": "CMSC 21", "name": "CMSC 21", "credits": 3, "requiredLab": true },
  { "id": "S_CMSC142", "code": "CMSC 142", "name": "CMSC 142", "credits": 3, "requiredLab": true },
  { "id": "S_CMSC143", "code": "CMSC 143", "name": "CMSC 143", "credits": 3, "requiredLab": true },
  { "id": "S_CMSC133", "code": "CMSC 133", "name": "CMSC 133", "credits": 3, "requiredLab": true },
  { "id": "S_CMSC134", "code": "CMSC 134", "name": "CMSC 134", "credits": 3, "requiredLab": true },
  { "id": "S_Philo21", "code": "Philo 21", "name": "Philo 21", "credits": 3, "requiredLab": false },
  { "id": "S_Major11", "code": "Major 11", "name": "Major 11", "credits": 3, "requiredLab": false },
  { "id": "S_Major12", "code": "Major 12", "name": "Major 12", "credits": 3, "requiredLab": false },
  { "id": "S_Hum11", "code": "Hum 11", "name": "Hum 11", "credits": 3, "requiredLab": false },
  { "id": "S_Spanish21", "code": "Spanish 21", "name": "Spanish 21", "credits": 3, "requiredLab": false },
  { "id": "S_NatSci21", "code": "NatSci 21", "name": "NatSci 21", "credits": 7, "requiredLab": false },
  { "id": "S_Physics21", "code": "Physics 21", "name": "Physics 21", "credits": 7, "requiredLab": false },
  { "id": "S_Biol22", "code": "Biol 22", "name": "Biol 22", "credits": 5, "requiredLab": false },
  { "id": "S_Rizal21", "code": "Rizal 21", "name": "Rizal 21", "credits": 3, "requiredLab": false },
  { "id": "S_Fil31", "code": "Fil 31", "name": "Fil 31", "credits": 3, "requiredLab": false },
  { "id": "S_FTE05", "code": "FTE 05", "name": "FTE 05", "credits": 3, "requiredLab": false },
  { "id": "S_FTE07", "code": "FTE 07", "name": "FTE 07", "credits": 7, "requiredLab": false },
  { "id": "S_FTE16", "code": "FTE 16", "name": "FTE 16", "credits": 6, "requiredLab": false },
  { "id": "S_FTE20", "code": "FTE 20", "name": "FTE 20", "credits": 3, "requiredLab": false },
  { "id": "S_FTE21", "code": "FTE 21", "name": "FTE 21", "credits": 3, "requiredLab": false },
  { "id": "S_FTE22", "code": "FTE 22", "name": "FTE 22", "credits": 3, "requiredLab": false },
  { "id": "S_FTE08", "code": "FTE 08", "name": "FTE 08", "credits": 3, "requiredLab": false },
  { "id": "S_FTE09", "code": "FTE 09", "name": "FTE 09", "credits": 7, "requiredLab": false },
  { "id": "S_FTE11", "code": "FTE 11", "name": "FTE 11", "credits": 3, "requiredLab": false },
  { "id": "S_Major08", "code": "Major 08", "name": "Major 08", "credits": 3, "requiredLab": false },
  { "id": "S_Major10", "code": "Major 10", "name": "Major 10", "credits": 3, "requiredLab": false },
  { "id": "S_Major13", "code": "Major 13", "name": "Major 13", "credits": 3, "requiredLab": false },
  { "id": "S_FTE17", "code": "FTE 17", "name": "FTE 17", "credits": 3, "requiredLab": false },
  { "id": "S_FTE18", "code": "FTE 18", "name": "FTE 18", "credits": 3, "requiredLab": false },
  { "id": "S_FTE19", "code": "FTE 19", "name": "FTE 19", "credits": 3, "requiredLab": false },
  { "id": "S_Agri21", "code": "Agri 21", "name": "Agri 21", "credits": 3, "requiredLab": false },
  { "id": "S_Major14", "code": "Major 14", "name": "Major 14", "credits": 3, "requiredLab": false },
  { "id": "S_Major09", "code": "Major 09", "name": "Major 09", "credits": 3, "requiredLab": false },
  { "id": "S_Typing2", "code": "Typing 2", "name": "Typing 2", "credits": 3, "requiredLab": false },
  { "id": "S_Steno2", "code": "Steno 2", "name": "Steno 2", "credits": 3, "requiredLab": false },
  { "id": "S_AppliedResearch2", "code": "Applied Research 2", "name": "Applied Research 2", "credits": 6, "requiredLab": false },
  { "id": "S_Speech11", "code": "Speech 11", "name": "Speech 11", "credits": 3, "requiredLab": false },
  { "id": "S_CWTS", "code": "CWTS", "name": "CWTS", "credits": 9, "requiredLab": false },
  { "id": "S_ROTC", "code": "ROTC", "name": "ROTC", "credits": 3, "requiredLab": false },
  { "id": "S_SocSci21", "code": "SocSci 21", "name": "SocSci 21", "credits": 3, "requiredLab": false },
  { "id": "S_English4", "code": "English 4", "name": "English 4", "credits": 5, "requiredLab": false },
  { "id": "S_English", "code": "English +", "name": "English +", "credits": 3, "requiredLab": false },
  { "id": "S_English41", "code": "English 41", "name": "English 41", "credits": 3, "requiredLab": false },
  { "id": "S_Major02", "code": "Major 02", "name": "Major 02", "credits": 3, "requiredLab": false },
  { "id": "S_Socio41", "code": "Socio 41", "name": "Socio 41", "credits": 3, "requiredLab": false },
  { "id": "S_Elective01", "code": "Elective 01", "name": "Elective 01", "credits": 3, "requiredLab": false },
  { "id": "S_Major0508", "code": "Major 05/08", "name": "Major 05/08", "credits": 3, "requiredLab": false },
  { "id": "S_Major0609", "code": "Major 06/09", "name": "Major 06/09", "credits": 3, "requiredLab": false }
];

export const initialSections = [
  { "id": "SEC_4thyearHighSchool", "name": "4th year High School", "subjects": ["S_English4", "S_Math4"] },
  { "id": "SEC_CS1A", "name": "CS 1A", "subjects": ["S_CMSC2", "S_CP12", "S_English11", "S_CMSC11", "S_Math11a", "S_Hum11"] },
  { "id": "SEC_CS1B", "name": "CS 1B", "subjects": ["S_CMSC2", "S_CP12", "S_English11", "S_Math11a", "S_Hum11", "S_CMSC12"] },
  { "id": "SEC_AB1", "name": "AB 1", "subjects": ["S_Math11a", "S_English11"] },
  { "id": "SEC_CS2A", "name": "CS 2A", "subjects": ["S_Fil21", "S_CP24", "S_Math21", "S_English21", "S_SocSci21", "S_CMSC21", "S_CMSC51"] },
  { "id": "SEC_CS2B", "name": "CS 2B", "subjects": ["S_Fil21", "S_CP24", "S_English21", "S_Math21", "S_SocSci21", "S_CMSC22", "S_CMSC51"] },
  { "id": "SEC_Prog2", "name": "Prog. 2", "subjects": ["S_Typing2", "S_CP24", "S_Steno2"] },
  { "id": "SEC_CPCS2A", "name": "CP/CS 2A", "subjects": ["S_Fil21"] },
  { "id": "SEC_CPCS2B", "name": "CP/CS 2B", "subjects": ["S_Fil21"] },
  { "id": "SEC_AB2", "name": "AB 2", "subjects": ["S_Lit21", "S_English21"] },
  { "id": "SEC_FTE2", "name": "FTE 2", "subjects": ["S_Lit21"] },
  { "id": "SEC_CS3A", "name": "CS 3A", "subjects": ["S_Lit31"] },
  { "id": "SEC_CS3", "name": "CS 3", "subjects": ["S_CMSC132", "S_CMSC131"] },
  { "id": "SEC_CS4", "name": "CS 4", "subjects": ["S_CMSCElective", "S_CP22", "S_FreeElective", "S_CMSC141"] },
  { "id": "SEC_AB3", "name": "AB 3", "subjects": ["S_English31"] },
  { "id": "SEC_Prog1", "name": "Prog. 1", "subjects": ["S_CP12"] },
  { "id": "SEC_Sec2", "name": "Sec. 2", "subjects": ["S_Typing2", "S_Steno2"] },
  { "id": "SEC_FTE1", "name": "FTE 1", "subjects": ["S_English11"] },
  { "id": "SEC_FTE3", "name": "FTE 3", "subjects": ["S_English31"] },
  { "id": "SEC_FTE4", "name": "FTE 4", "subjects": ["S_English41"] },
  { "id": "SEC_Sec1", "name": "Sec. 1", "subjects": ["S_CP14"] },
  { "id": "SEC_ABEng2", "name": "AB Eng 2", "subjects": ["S_Major02"] },
  { "id": "SEC_ABFTE1", "name": "AB/FTE 1", "subjects": ["S_Hum11"] },
  { "id": "SEC_AB4", "name": "AB 4", "subjects": ["S_Elective01", "S_Socio41"] },
  { "id": "SEC_CSCourses", "name": "CS Courses", "subjects": ["S_English"] },
  { "id": "SEC_CS4a", "name": "CS 4AS", "subjects": ["S_English41"] }
];