// src/initial.js
// CAPSU Mambusao Official Data (Loading_2nd-2025-2026 superfinal) - CLEANED

export const initialRooms = [
  { id: "R_ScienceLab", name: "Science Lab", type: "Laboratory", hasComputers: true, hasProjector: true },
  { id: "R_GymFTE", name: "Gym FTE", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_FoodPro", name: "Food Pro", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_PhysicoChem", name: "Physico Chem", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_FTELectRoom", name: "FTE Lect Room", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Flavier", name: "Flavier", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Gym4", name: "Gym 4", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Gym3", name: "Gym 3", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Gym2", name: "Gym 2", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Gym", name: "Gym", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Stage", name: "Stage", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_MULTIMEDIAROOM", name: "MULTIMEDIA ROOM", type: "Laboratory", hasComputers: true, hasProjector: true },
  { id: "R_GS7", name: "GS 7", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS6", name: "GS 6", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS5", name: "GS 5", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS4", name: "GS 4", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS3", name: "GS 3", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS2", name: "GS 2", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_GS1", name: "GS 1", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_SpeechLab", name: "Speech Lab", type: "Laboratory", hasComputers: true, hasProjector: true },
  { id: "R_Room204", name: "Room 204", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Room203", name: "Room 203", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Room102", name: "Room 102", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_Room101", name: "Room 101", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB6", name: "NB 6", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB5", name: "NB 5", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB4", name: "NB 4", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB3", name: "NB 3", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB2", name: "NB 2", type: "Lecture", hasComputers: false, hasProjector: true },
  { id: "R_NB1", name: "NB 1", type: "Lecture", hasComputers: false, hasProjector: true }
];

export const initialProfessors = [
  { id: "P_0", name: "Ma. Relie Aguilos", department: "General Education", maxUnits: 24, specialization: ["S_GEM101", "S_GE107"], preferredRooms: [] },
  { id: "P_1", name: "Regine Aller", department: "General Education", maxUnits: 24, specialization: ["S_OAC121", "S_GEE109"], preferredRooms: [] },
  { id: "P_2", name: "Kimberly Azarcon", department: "General Education", maxUnits: 24, specialization: ["S_PE110", "S_GEE103"], preferredRooms: [] },
  { id: "P_3", name: "Janice Ballera", department: "General Education", maxUnits: 24, specialization: ["S_PE112"], preferredRooms: [] },
  { id: "P_4", name: "Sherra Baje", department: "Computer Science", maxUnits: 24, specialization: ["S_CS107", "S_CS108"], preferredRooms: [] },
  { id: "P_5", name: "Herman Baranda", department: "General Education", maxUnits: 24, specialization: ["S_NSTP102"], preferredRooms: [] },
  { id: "P_6", name: "Cynthren Bernabe", department: "General Education", maxUnits: 24, specialization: ["S_GE107"], preferredRooms: [] },
  { id: "P_7", name: "Lecel Bobier", department: "General Education", maxUnits: 24, specialization: ["S_OAC114"], preferredRooms: [] },
  { id: "P_8", name: "Nicolas Braña", department: "Computer Science", maxUnits: 24, specialization: ["S_CS107lec", "S_CS103"], preferredRooms: [] },
  { id: "P_9", name: "Vincent Bunda", department: "General Education", maxUnits: 24, specialization: ["S_GEE102"], preferredRooms: [] },
  { id: "P_10", name: "Lida Corcino", department: "General Education", maxUnits: 24, specialization: ["S_GE106"], preferredRooms: [] },
  { id: "P_11", name: "Julie Dalida", department: "General Education", maxUnits: 24, specialization: ["S_GE108"], preferredRooms: [] },
  { id: "P_12", name: "Nino Dela Cena", department: "Computer Science", maxUnits: 24, specialization: ["S_CS111"], preferredRooms: [] },
  { id: "P_13", name: "Freden Delgado", department: "General Education", maxUnits: 24, specialization: ["S_ELSM119", "S_ELSC111", "S_OAC117"], preferredRooms: [] },
  { id: "P_14", name: "Mischelle Espartero", department: "General Education", maxUnits: 24, specialization: ["S_GE107"], preferredRooms: [] },
  { id: "P_15", name: "Merlyn Filosofo", department: "General Education", maxUnits: 24, specialization: ["S_FL103", "S_CBM102", "S_ELSM119", "S_ELSM115"], preferredRooms: [] },
  { id: "P_16", name: "Bethel Jane Iligan", department: "General Education", maxUnits: 24, specialization: ["S_OAC111", "S_CBM102"], preferredRooms: [] },
  { id: "P_17", name: "June Rey Garbosa", department: "General Education", maxUnits: 24, specialization: ["S_GE109"], preferredRooms: [] },
  { id: "P_18", name: "Marife Hilapad", department: "General Education", maxUnits: 24, specialization: ["S_FTC107", "S_FTC111"], preferredRooms: [] },
  { id: "P_19", name: "Lillibeth Leonor", department: "General Education", maxUnits: 24, specialization: ["S_GE108", "S_FTC105"], preferredRooms: [] },
  { id: "P_20", name: "Olga Llanera", department: "Computer Science", maxUnits: 24, specialization: ["S_CS108", "S_CS118"], preferredRooms: [] },
  { id: "P_21", name: "Ricah Llorito", department: "General Education", maxUnits: 24, specialization: ["S_GE106"], preferredRooms: [] },
  { id: "P_22", name: "Rosemarie Luces", department: "General Education", maxUnits: 24, specialization: ["S_GEE102"], preferredRooms: [] },
  { id: "P_23", name: "Virginia Magbanua", department: "General Education", maxUnits: 24, specialization: ["S_OAC114"], preferredRooms: [] },
  { id: "P_24", name: "Meschel Marcos", department: "General Education", maxUnits: 24, specialization: ["S_CBM102", "S_ELSM115", "S_ELSM121"], preferredRooms: [] },
  { id: "P_25", name: "Lizel Marquez", department: "General Education", maxUnits: 24, specialization: ["S_FTM102", "S_FTE103", "S_FTM106"], preferredRooms: [] },
  { id: "P_26", name: "Shiela Martinez", department: "General Education", maxUnits: 24, specialization: ["S_GEM101", "S_GE103"], preferredRooms: [] },
  { id: "P_27", name: "Frocy Navarrosa", department: "Computer Science", maxUnits: 24, specialization: ["S_CS109"], preferredRooms: [] },
  { id: "P_28", name: "Art Jayson Osuyos", department: "Computer Science", maxUnits: 24, specialization: ["S_FreeElective102lec", "S_CS110", "S_FreeElective102", "S_CS109"], preferredRooms: [] },
  { id: "P_29", name: "Cherry Joy Palomar", department: "Computer Science", maxUnits: 24, specialization: ["S_CS120", "S_CSElective102"], preferredRooms: [] },
  { id: "P_30", name: "Jelly Paredes", department: "Computer Science", maxUnits: 24, specialization: ["S_CS119", "S_Seminar301"], preferredRooms: [] },
  { id: "P_31", name: "Leo Pula", department: "General Education", maxUnits: 24, specialization: ["S_FreeElective104", "S_ELS110"], preferredRooms: [] },
  { id: "P_32", name: "Lalaine Ricardo", department: "General Education", maxUnits: 24, specialization: ["S_GE109"], preferredRooms: [] },
  { id: "P_33", name: "Rhodora Ticar", department: "General Education", maxUnits: 24, specialization: ["S_GEE103", "S_Chem102"], preferredRooms: [] },
  { id: "P_34", name: "Maria Aurora Victoriano", department: "General Education", maxUnits: 24, specialization: ["S_FL103", "S_FL101", "S_ELSM128", "S_ELS103"], preferredRooms: [] },
  { id: "P_35", name: "Judith Vista", department: "Computer Science", maxUnits: 24, specialization: ["S_CS117", "S_CS116"], preferredRooms: [] },

];

export const initialSubjects = [
  { id: "S_GEM101", code: "GEM 101", name: "Life and Works of Rizal", credits: 3.0, requiredLab: false },
  { id: "S_GE107", code: "GE 107", name: "Ethics", credits: 3.0, requiredLab: false },
  { id: "S_OAC121", code: "OAC 121", name: "Internet Research for Business", credits: 3.0, requiredLab: true },
  { id: "S_GEE109", code: "GEE 109", name: "Entrepreneurial Mind", credits: 3.0, requiredLab: false },
  { id: "S_PE110", code: "PE 110", name: "PATHFit 2", credits: 2.0, requiredLab: false },
  { id: "S_GEE103", code: "GEE 103", name: "Living in the IT Era", credits: 3.0, requiredLab: false },
  { id: "S_PE112", code: "PE 112", name: "PATHFit 4", credits: 2.0, requiredLab: false },
  { id: "S_CS107", code: "CS 107", name: "Intro. to Human-Computer Interaction", credits: 3.0, requiredLab: true },
  { id: "S_CS108", code: "CS 108", name: "Programming 2", credits: 3.0, requiredLab: true },
  { id: "S_NSTP102", code: "NSTP 102", name: "CWTS 2", credits: 3.0, requiredLab: false },
  { id: "S_OAC114", code: "OAC 114", name: "Administrative Office Procedures", credits: 3.0, requiredLab: false },
  { id: "S_CS107lec", code: "CS 107 (lec)", name: "Intro. to Human-Computer Interaction", credits: 3.0, requiredLab: false },
  { id: "S_CS103", code: "CS 103", name: "Intro to Computing", credits: 3.0, requiredLab: true },
  { id: "S_GEE102", code: "GEE 102", name: "The Contemporary World", credits: 3.0, requiredLab: false },
  { id: "S_GE106", code: "GE 106", name: "Purposive Communication", credits: 3.0, requiredLab: false },
  { id: "S_GE108", code: "GE 108", name: "Science, Technology, and Society", credits: 3.0, requiredLab: false },
  { id: "S_CS111", code: "CS 111", name: "IT Elective 1", credits: 3.0, requiredLab: true },
  { id: "S_OAC117", code: "OAC 117", name: "Business Report Writing", credits: 3.0, requiredLab: false },
  { id: "S_ELSM119", code: "ELSM 119", name: "Language Programs and Policies in Multilingual Societies", credits: 3.0, requiredLab: false },
  { id: "S_ELSC111", code: "ELSC 111", name: "Sanaysay at Talumpati", credits: 3.0, requiredLab: false },
  { id: "S_CBM102", code: "CBM 102", name: "Human Resource Management", credits: 3.0, requiredLab: false },
  { id: "S_ELSM115", code: "ELSM 115", name: "Literary Criticism", credits: 3.0, requiredLab: false },
  { id: "S_FL103", code: "FL 103", name: "Foreign Language 3", credits: 3.0, requiredLab: false },
  { id: "S_OAC111", code: "OAC 111", name: "Business Communication", credits: 3.0, requiredLab: false },
  { id: "S_GE109", code: "GE 109", name: "Readings in Philippine History", credits: 3.0, requiredLab: false },
  { id: "S_FTC107", code: "FTC 107", name: "Chemistry for Food Science", credits: 5.0, requiredLab: true },
  { id: "S_FTC111", code: "FTC 111", name: "Physical Chemistry", credits: 5.0, requiredLab: true },
  { id: "S_FTC105", code: "FTC 105", name: "Food Microbiology", credits: 5.0, requiredLab: true },
  { id: "S_CS118", code: "CS 118", name: "Software Engineering II", credits: 3.0, requiredLab: true },
  { id: "S_ELSM121", code: "ELSM 121", name: "Stylistics and Discourse Analysis", credits: 3.0, requiredLab: false },
  { id: "S_FTE103", code: "FTE 103", name: "Unit Operations in Food Processing I", credits: 3.0, requiredLab: false },
  { id: "S_FTM102", code: "FTM 102", name: "Post-Harvest Handling & Tech.", credits: 3.0, requiredLab: true },
  { id: "S_FTM106", code: "FTM 106", name: "Food Safety", credits: 3.0, requiredLab: true },
  { id: "S_GE103", code: "GE 103", name: "Mathematics in the Modern World", credits: 3.0, requiredLab: false },
  { id: "S_CS109", code: "CS 109", name: "Discrete Mathematics", credits: 3.0, requiredLab: false },
  { id: "S_FreeElective102", code: "Free Elective 102", name: "Free Elective 2", credits: 3.0, requiredLab: true },
  { id: "S_CS110", code: "CS 110", name: "Intro to Data Science", credits: 3.0, requiredLab: true },
  { id: "S_FreeElective102lec", code: "Free Elective 102 (lec)", name: "Free Elective 2", credits: 3.0, requiredLab: false },
  { id: "S_CSElective102", code: "CS Elective 102", name: "CS Elective 2", credits: 3.0, requiredLab: true },
  { id: "S_CS120", code: "CS 120", name: "Networks & Communications", credits: 3.0, requiredLab: true },
  { id: "S_CS119", code: "CS 119", name: "Information Assurance & Security", credits: 3.0, requiredLab: true },
  { id: "S_Seminar301", code: "Seminar 301", name: "Seminar and Field Trip", credits: 3.0, requiredLab: false },
  { id: "S_FreeElective104", code: "Free Elective 104", name: "Free Elective 4", credits: 3.0, requiredLab: true },
  { id: "S_ELS110", code: "ELS 110", name: "Survey of English and American Literature", credits: 3.0, requiredLab: false },
  { id: "S_Chem102", code: "Chem 102", name: "Qualitative Chemistry", credits: 5.0, requiredLab: true },
  { id: "S_FL101", code: "FL 101", name: "Foreign Language 1", credits: 3.0, requiredLab: false },
  { id: "S_ELS103", code: "ELS 103", name: "History of the English Language", credits: 3.0, requiredLab: false },
  { id: "S_ELSM128", code: "ELSM 128", name: "Philippine English", credits: 3.0, requiredLab: false },
  { id: "S_CS116", code: "CS 116", name: "Design and Implementation of Programming Language", credits: 5.0, requiredLab: true },
  { id: "S_CS117", code: "CS 117", name: "Computer Architecture & Assembly Programming", credits: 5.0, requiredLab: true },
  { id: "S_OAC123", code: "OAC 123", name: "Customer Relations", credits: 3.0, requiredLab: false },
  { id: "S_OAC119", code: "OAC 119", name: "Machine Shorthand", credits: 3.0, requiredLab: true },
  { id: "S_CS124", code: "CS 124", name: "Thesis Writing II", credits: 3.0, requiredLab: true },
  { id: "S_OJT", code: "OJT", name: "Practicum (162 hrs.)", credits: 3.0, requiredLab: false },
  { id: "S_FTC103", code: "FTC 103", name: "Food Processing", credits: 5.0, requiredLab: true },
  { id: "S_FTE107", code: "FTE 107", name: "Meat Processing", credits: 3.0, requiredLab: true },
  { id: "S_FTE106", code: "FTE 106", name: "Food Packaging and Labeling", credits: 3.0, requiredLab: true },
  { id: "S_ELSM117", code: "ELSM 117", name: "Afro-Asian Literature", credits: 3.0, requiredLab: false },
  { id: "S_OAEL116", code: "OAEL 116", name: "Events Management", credits: 3.0, requiredLab: false },
  { id: "S_FTE105", code: "FTE 105", name: "Product Development and Innovation", credits: 3.0, requiredLab: true }
];

export const initialSections = [
  { id: "SEC_BSCS2A", name: "BSCS 2A", subjects: ["S_CS107lec", "S_GEM101", "S_CS109", "S_CS111", "S_CS108", "S_PE112"] },
  { id: "SEC_BSCS2B", name: "BSCS 2B", subjects: ["S_CS107", "S_GEM101", "S_CS109", "S_CS111", "S_CS108", "S_CS110", "S_PE112"] },
  { id: "SEC_BSCS2C", name: "BSCS 2C", subjects: ["S_CS107lec", "S_GEM101", "S_CS109", "S_CS111", "S_CS108", "S_PE112"] },
  { id: "SEC_BAEL1", name: "BAEL 1", subjects: ["S_GE109", "S_GE107", "S_NSTP102", "S_ELS103", "S_PE110"] },
  { id: "SEC_BSFT1A", name: "BSFT 1A", subjects: ["S_GE109", "S_GE107", "S_NSTP102", "S_GE106", "S_PE110"] },
  { id: "SEC_BSOA3A", name: "BSOA 3A", subjects: ["S_OAC121"] },
  { id: "SEC_BSOA3B", name: "BSOA 3B", subjects: ["S_OAC121"] },
  { id: "SEC_BSFT4A", name: "BSFT 4A", subjects: ["S_GEM101", "S_GEE109"] },
  { id: "SEC_BSFT4B", name: "BSFT 4B", subjects: ["S_GEM101", "S_GEE109"] },
  { id: "SEC_BSFT4C", name: "BSFT 4C", subjects: ["S_GEM101", "S_GEE109"] },
  { id: "SEC_BSCS1A", name: "BSCS 1A", subjects: ["S_GE108", "S_CS103", "S_GE106", "S_PE110"] },
  { id: "SEC_BSCS1C", name: "BSCS 1C", subjects: ["S_GE109", "S_GE108", "S_GE106", "S_PE110"] },
  { id: "SEC_BSCS1B", name: "BSCS 1B", subjects: ["S_GE108", "S_CS103", "S_GE106", "S_PE110"] },
  { id: "SEC_BSFT2A", name: "BSFT 2A", subjects: ["S_GEE103", "S_FTC103", "S_FTM102", "S_FTE103", "S_PE112"] },
  { id: "SEC_BSFT2B", name: "BSFT 2B", subjects: ["S_GEE103", "S_FTC103", "S_FTM102", "S_FTE103", "S_PE112"] },
  { id: "SEC_BSCS2D", name: "BSCS 2D", subjects: ["S_CS107lec", "S_GEM101", "S_CS109", "S_CS111", "S_CS108", "S_PE112"] },
  { id: "SEC_BSFT1", name: "BSFT 1", subjects: ["S_GE108", "S_GE106", "S_Chem102"] },
  { id: "SEC_BSOA1", name: "BSOA 1", subjects: ["S_OAC114", "S_GE104", "S_NSTP102", "S_OAC111", "S_PE110"] },
  { id: "SEC_BAEL4", name: "BAEL 4", subjects: ["S_ELSM119", "S_ELSM128", "S_ELSM121"] },
  { id: "SEC_BAEL3", name: "BAEL 3", subjects: ["S_FL103", "S_ELSM115", "S_ELSM117"] },
  { id: "SEC_BSOA2", name: "BSOA 2", subjects: ["S_CBM102", "S_OAC117", "S_OAC119", "S_PE112"] },
  { id: "SEC_BSFT3A", name: "BSFT 3A", subjects: ["S_FTC105", "S_FTM106", "S_FTC107", "S_FTC111", "S_FTE105"] },
  { id: "SEC_BSFT3B", name: "BSFT 3B", subjects: ["S_FTC105", "S_FTC107", "S_FTE107", "S_FTE106"] },
  { id: "SEC_BSFT3C", name: "BSFT 3C", subjects: ["S_FTC105", "S_FTC107", "S_FTM106", "S_FTE107", "S_FTE106"] },
  { id: "SEC_BAEL2", name: "BAEL 2", subjects: ["S_ELSC111", "S_FL101", "S_ELS110", "S_PE112"] },
  { id: "SEC_BSCS1D", name: "BSCS 1D", subjects: ["S_GE109", "S_GE107", "S_NSTP102", "S_GE106"] },
  { id: "SEC_BSCS3A", name: "BSCS 3A", subjects: ["S_CS117", "S_CS116", "S_Seminar301", "S_FreeElective102lec", "S_CS120", "S_CS119", "S_CSElective102"] },
  { id: "SEC_BSCS3B", name: "BSCS 3B", subjects: ["S_CS117", "S_CS116", "S_Seminar301", "S_FreeElective102", "S_CS120", "S_CS119", "S_CSElective102"] },
  { id: "SEC_BSCS3C", name: "BSCS 3C", subjects: ["S_CS117", "S_CS118", "S_CS116", "S_Seminar301", "S_FreeElective102", "S_CS120", "S_CS119", "S_CSElective102"] },
  { id: "SEC_BSOA4A", name: "BSOA 4A", subjects: ["S_OAEL116"] },
  { id: "SEC_BSOA4B", name: "BSOA 4B", subjects: ["S_OAEL116"] },
  { id: "SEC_BSCS4A", name: "BSCS 4A", subjects: ["S_OJT", "S_CS124", "S_FreeElective104"] },
  { id: "SEC_BSCS4B", name: "BSCS 4B", subjects: ["S_OJT", "S_CS124", "S_FreeElective104"] },
  { id: "SEC_BSCS4C", name: "BSCS 4C", subjects: ["S_OJT", "S_CS124", "S_FreeElective104"] }
];